name: smartamrX
channels:
  - bioconda
  - conda-forge
dependencies:
  - ipykernel
  - seaborn
  - matplotlib
  - xgboost
  - scikit-learn
  - pytorch
  - keras
  - pandas
  - numpy
  - biopython
  - pip:
    - fair-esm
